[package]
name = "veloc-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
veloc-ir = { path = "../ir" }
cranelift-entity = { workspace = true }
object = { version = "0.36", features = ["write"] }
hashbrown = { workspace = true }


[features]
default = ["std"]
std = ["veloc-ir/std"]


