[package]
name = "veloc_interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
veloc_ir = { workspace = true }
veloc_analyzer = { workspace = true }
hashbrown = { workspace = true }
cranelift-entity = { workspace = true }
libm = "0.2"

[features]
default = ["std"]
std = ["veloc_ir/std"]


