[package]
name = "veloc_interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
veloc_ir = { path = "../ir" }
hashbrown = { workspace = true }

[features]
default = ["std"]
std = ["veloc_ir/std"]


