[package]
name = "veloc_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
veloc_ir = { path = "../ir" }
cranelift-entity = { workspace = true }
object = { version = "0.36", features = ["write"] }
hashbrown = { workspace = true }


[features]
default = ["std"]
std = ["veloc_ir/std"]


