[package]
name = "veloc_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
veloc_ir = { workspace = true }
hashbrown = { workspace = true }
bitvec = { workspace = true }
cranelift-entity = { workspace = true }
